env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - plugin:react/jsx-runtime
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: "latest"
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: "detect"
ignorePatterns:
  - "**/node_modules/**"
  - "**/__mocks__/**/*.js"
  - "**/dist/**"
rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".jsx", ".tsx"] }]
}
