name: Release Alpha Workflow

on:
  push:
    branches:
      - 'releases/**-alpha'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract version from branch name
        id: extract_version
        run: echo "::set-output name=version::$(echo ${{ github.ref }} | sed -n 's/refs\/heads\/releases\/\(.*\)-alpha/\1/p')"
      - name: Extract rc from package.json
        id: extract_rc
        run: echo "::set-output name=rc::$(node -p "require('./package.json').version" | sed -n -e '/-alpha\./{s/.*\.\([0-9][0-9]*\)$/\1/p;q;}' -e 's/.*$/0/p')"
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Bump version and publish to npm
        run: |
          # Use the extracted version number for your release process
          npm version ${{ steps.extract_version.outputs.version }} prerelease --preid=alpha
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
      